theme: jekyll-theme-cayman
markdown: kramdown
title: Bioinformatics practical for the 2019 SING-Aotearoa session
description: A brief introduction to looking at new sequencing technologies.
author:
name: Patrick J Biggs
page-img: "SING_MaoriSun.jpg"
